# Generated by Django 4.0.1 on 2022-01-20 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_purchase_topic_transaction_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='details',
        ),
        migrations.AddField(
            model_name='transaction',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.purchase'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
