# Generated by Django 4.0.1 on 2022-01-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_transaction_details_transaction_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(default='Pending', max_length=60),
        ),
    ]
