# Generated by Django 4.0.1 on 2022-03-09 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_totaltransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='totaltransaction',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.group'),
        ),
    ]
