# Generated by Django 4.0.1 on 2022-03-10 08:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_group_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='picture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
